tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaaa5bukpynuqzpbvwwiomypkyqgqvv42thtgjtbblhxphvnfkxpayq"
user_ocid = "ocid1.user.oc1..aaaaaaaadodpovo5vjo7slnwp2fmakt2yjcygx2hkp5zvn3fhjig3lx5lmbq"
fingerprint = "ea:f0:87:d0:d0:21:2c:cf:81:63:49:ea:1a:fa:29:16"
private_key_path = "~/.oci/oci_api_key.pem"
compartment_ocid = "ocid1.compartment.oc1..aaaaaaaayqd3n2lkibduy7qarxvnyk6cznsuxyovacdonz4lcno27sf74qta"
region = "eu-frankfurt-1"
fqdn = "rallly.147160.xyz"
rallly_smtp_credential_username = "<username>"
# If the SMTP credential includes a $ make sure to escape it in the secret \$ - totally docker compose's fault (env-file)
rallly_smtp_credential_secret_ocid = "<secret_ocid>"
rallly-container-tag = "4.7.4"
