tenancy_ocid = "<tenancy_ocid>"
current_user_ocid = "<current_user_ocid>"
fingerprint = "<private_key_fingerprint>"
private_key_path = "~/.oci/oci_api_key.pem"
compartment_ocid = "<compartment_ocid>"
region = "eu-frankfurt-1"
fqdn = "rallly.example.com"
identity_domain = "<identity_domain_ocid>"
rallly_smtp_credential_username = "<username>"
# If the SMTP credential includes a $ make sure to escape it in the secret \$ - totally docker compose's fault (env-file)
rallly_smtp_credential_secret_ocid = "<secret_ocid>"
rallly-container-tag = "4.7.4"
